import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'cli/index': 'src/cli/index.ts',
    'client/index': 'src/client/index.ts',
    'ir/index': 'src/ir/index.ts',
    'capabilities/index': 'src/capabilities/index.ts',
    'planner/index': 'src/planner/index.ts',
    'adapters/index': 'src/adapters/index.ts',
    'adapters/mysql/index': 'src/adapters/mysql/index.ts',
    'adapters/mongodb/index': 'src/adapters/mongodb/index.ts',
    'adapters/postgres/index': 'src/adapters/postgres/index.ts',
    'adapters/sqlite/index': 'src/adapters/sqlite/index.ts',
    'cache/index': 'src/cache/index.ts',
    'schema/index': 'src/schema/index.ts',
    'migration/index': 'src/migration/index.ts',
    'security/index': 'src/security/index.ts',
    'observability/index': 'src/observability/index.ts',
    'realtime/index': 'src/realtime/index.ts',
    'analyzers/index': 'src/analyzers/index.ts',
    'errors/index': 'src/errors/index.ts',
    'compat/index': 'src/compat/index.ts',
    'compat/mysql2': 'src/compat/mysql2.ts',
    'compat/pg': 'src/compat/pg.ts',
    'compat/mysql': 'src/compat/mysql.ts',
    'compat/mongodb': 'src/compat/mongodb.ts',
    'compat/mongoose': 'src/compat/mongoose.ts',
    'compat/register': 'src/compat/register.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  minify: false,
  outDir: 'dist',
  target: 'node18',
  banner: {
    js: '#!/usr/bin/env node',
  },
  external: ['mysql2', 'mongodb', 'pg', 'better-sqlite3'],
  noExternal: ['dotenv', 'commander', 'chalk', 'ora', 'table'],
  onSuccess: 'echo "JSDB build complete"',
});
